// Generated by dart2js, the Dart to JavaScript compiler.
(function($){var A={}
delete A.x
var B={}
delete B.x
var C={}
delete C.x
var D={}
delete D.x
var E={}
delete E.x
var F={}
delete F.x
var G={}
delete G.x
var H={}
delete H.x
var J={}
delete J.x
var K={}
delete K.x
var L={}
delete L.x
var M={}
delete M.x
var N={}
delete N.x
var O={}
delete O.x
var P={}
delete P.x
var Q={}
delete Q.x
var R={}
delete R.x
var S={}
delete S.x
var T={}
delete T.x
var U={}
delete U.x
var V={}
delete V.x
var W={}
delete W.x
var X={}
delete X.x
var Y={}
delete Y.x
var Z={}
delete Z.x
function I(){}
init()
$=I.p
var $$={}
$$.yh=[H,{"":"Tp;call$0,$name"}]
$$.Pz=[H,{"":"Tp;call$7,$name"}]
;(function (reflectionData) {
  function map(x){x={x:x};delete x.x;return x}
  if (!init.libraries) init.libraries = [];
  if (!init.mangledNames) init.mangledNames = map();
  if (!init.mangledGlobalNames) init.mangledGlobalNames = map();
  if (!init.statics) init.statics = map();
  if (!init.typeInformation) init.typeInformation = map();
  if (!init.globalFunctions) init.globalFunctions = map();
  var libraries = init.libraries;
  var mangledNames = init.mangledNames;
  var mangledGlobalNames = init.mangledGlobalNames;
  var hasOwnProperty = Object.prototype.hasOwnProperty;
  var length = reflectionData.length;
  for (var i = 0; i < length; i++) {
    var data = reflectionData[i];
    var name = data[0];
    var uri = data[1];
    var metadata = data[2];
    var globalObject = data[3];
    var descriptor = data[4];
    var isRoot = !!data[5];
    var fields = descriptor && descriptor[""];
    var classes = [];
    var functions = [];
    function processStatics(descriptor) {
      for (var property in descriptor) {
        if (!hasOwnProperty.call(descriptor, property)) continue;
        if (property === "") continue;
        var element = descriptor[property];
        var firstChar = property.substring(0, 1);
        var previousProperty;
        if (firstChar === "+") {
          mangledGlobalNames[previousProperty] = property.substring(1);
          if (descriptor[property] == 1) descriptor[previousProperty].$reflectable = 1;
          if (element && element.length) init.typeInformation[previousProperty] = element;
        } else if (firstChar === "@") {
          property = property.substring(1);
          $[property]["@"] = element;
        } else if (firstChar === "*") {
          globalObject[previousProperty].$defaultValues = element;
          var optionalMethods = descriptor.$methodsWithOptionalArguments;
          if (!optionalMethods) {
            descriptor.$methodsWithOptionalArguments = optionalMethods = {}
          }
          optionalMethods[property] = previousProperty;
        } else if (typeof element === "function") {
          globalObject[previousProperty = property] = element;
          functions.push(property);
          init.globalFunctions[property] = element;
        } else {
          previousProperty = property;
          var newDesc = {};
          var previousProp;
          for (var prop in element) {
            if (!hasOwnProperty.call(element, prop)) continue;
            firstChar = prop.substring(0, 1);
            if (prop === "static") {
              processStatics(init.statics[property] = element[prop]);
            } else if (firstChar === "+") {
              mangledNames[previousProp] = prop.substring(1);
              if (element[prop] == 1) element[previousProp].$reflectable = 1;
            } else if (firstChar === "@" && prop !== "@") {
              newDesc[prop.substring(1)]["@"] = element[prop];
            } else if (firstChar === "*") {
              newDesc[previousProp].$defaultValues = element[prop];
              var optionalMethods = newDesc.$methodsWithOptionalArguments;
              if (!optionalMethods) {
                newDesc.$methodsWithOptionalArguments = optionalMethods={}
              }
              optionalMethods[prop] = previousProp;
            } else {
              newDesc[previousProp = prop] = element[prop];
            }
          }
          $$[property] = [globalObject, newDesc];
          classes.push(property);
        }
      }
    }
    processStatics(descriptor);
    libraries.push([name, uri, classes, functions, metadata, fields, isRoot,
                    globalObject]);
  }
})([["_foreign_helper","dart:_foreign_helper",,H,{FK:{"":"a;tT"}}],["_interceptors","dart:_interceptors",,J,{x:function(a){return void 0},Qu:function(a,b,c,d){return{i: a, p: b, e: c, x: d}},M3:function(a){var z,y,x,w
z=a[init.dispatchPropertyName]
if(z==null)if($.Bv==null){H.XD()
z=a[init.dispatchPropertyName]}if(z!=null){y=z.p
if(!1===y)return z.i
if(!0===y)return a
x=Object.getPrototypeOf(a)
if(y===x)return z.i
if(z.e===x)throw H.b(P.SY("Return interceptor for "+H.d(y(a,z))))}w=H.w3(a)
if(w==null)return C.vB
return w},Gv:{"":"a;",
n:function(a,b){return a===b},
giO:function(a){return H.eQ(a)},
bu:function(a){return H.o9(a)},
"%":"AutocompleteErrorEvent|DOMError|ErrorEvent|Event|FileError|Gamepad|MediaError|MediaKeyError|Navigator|NavigatorUserMediaError|PositionError|SQLError|SVGAnimatedLength|SVGRect|SpeechRecognitionError|WebGLBuffer|WebGLProgram|WebGLShader|WebGLUniformLocation"},yE:{"":"bool/Gv;",
bu:function(a){return String(a)}},CD:{"":"Gv;",
n:function(a,b){return!1},
bu:function(a){return"null"}},Ue:{"":"Gv;"},iC:{"":"Ue;"},is:{"":"Ue;"},Q:{"":"List/Gv;",
Zv:function(a,b){if(b<0||b>=a.length)throw H.e(a,b)
return a[b]},
bu:function(a){return H.mx(a,"[","]")},
gA:function(a){return new H.a7(a,a.length,0,null)},
gB:function(a){return a.length},
$isList:true},nM:{"":"Q;",
$asQ:function(){return[null]}},tN:{"":"nM;"},Jt:{"":"nM;"},P:{"":"num/Gv;",
bu:function(a){if(a===0&&1/a<0)return"-0.0"
else return""+a},
$isnum:true,
static:{"":"SA,nr",}},im:{"":"int/P;",$isnum:true,$isint:true},VA:{"":"double/P;",$isnum:true},O:{"":"String/Gv;",
j:function(a,b){if(b<0)throw H.b(P.N(b))
if(b>=a.length)throw H.b(P.N(b))
return a.charCodeAt(b)},
Nj:function(a,b,c){if(c==null)c=a.length
if(typeof c!=="number"||Math.floor(c)!==c)H.vh(P.u(c))
if(b<0)throw H.b(P.N(b))
if(typeof c!=="number")throw H.s(c)
if(b>c)throw H.b(P.N(b))
if(c>a.length)throw H.b(P.N(c))
return a.substring(b,c)},
yn:function(a,b){return this.Nj(a,b,null)},
bu:function(a){return a},
gB:function(a){return a.length},
$isString:true}}],["_js_helper","dart:_js_helper",,H,{wV:function(a,b){var z,y
if(b!=null){z=b.x
if(z!=null)return z}y=J.x(a)
return typeof a==="object"&&a!==null&&!!y.$isXj},d:function(a){var z
if(typeof a==="string")return a
if(typeof a==="number"){if(a!==0)return""+a}else if(!0===a)return"true"
else if(!1===a)return"false"
else if(a==null)return"null"
z=J.AG(a)
if(typeof z!=="string")throw H.b(P.u(a))
return z},eQ:function(a){var z=a.$identityHash
if(z==null){z=Math.random()*0x3fffffff|0
a.$identityHash=z}return z},lh:function(a){var z,y
z=C.Mo(J.x(a))
if(z==="Object"){y=String(a.constructor).match(/^\s*function\s*(\S*)\s*\(/)[1]
if(typeof y==="string")z=y}if(J.rY(z).j(z,0)===36)z=C.xB.yn(z,1)
return z+H.ia(H.oX(a),0,null)},o9:function(a){return"Instance of '"+H.lh(a)+"'"},rD:function(a){var z=new Array(a)
z.fixed$length=!0
return z},s:function(a){throw H.b(P.u(a))},e:function(a,b){if(a==null)J.q8(a)
if(typeof b!=="number"||Math.floor(b)!==b)H.s(b)
throw H.b(P.N(b))},b:function(a){var z
if(a==null)a=new P.LK()
z=new Error()
z.dartException=a
if("defineProperty" in Object){Object.defineProperty(z, "message", { get: H.Eu.call$0 })
z.name=""}else z.toString=H.Eu.call$0
return z},Ju:function(){return J.AG(this.dartException)},vh:function(a){throw H.b(a)},CU:function(a){if(typeof a!='object')return J.v1(a)
else return H.eQ(a)},ft:function(a,b,c,d,e,f,g){var z=J.x(c)
if(z.n(c,0))return new H.dr(a).call$0()
else if(z.n(c,1))return new H.TL(a,d).call$0()
else if(z.n(c,2))return new H.KX(a,d,e).call$0()
else if(z.n(c,3))return new H.uZ(a,d,e,f).call$0()
else if(z.n(c,4))return new H.OQ(a,d,e,f,g).call$0()
else throw H.b(P.FM("Unsupported number of arguments for wrapped closure"))},tR:function(a,b){var z
if(a==null)return
z=a.$identity
if(!!z)return z
z=(function(closure, arity, context, invoke) {  return function(a1, a2, a3, a4) {     return invoke(closure, context, arity, a1, a2, a3, a4);  };})(a,b,$,H.eH.call$7)
a.$identity=z
return z},ag:function(a){throw H.b(P.Gz("Cyclic initialization for static "+H.d(a)))},oX:function(a){if(a==null)return
return a.$builtinTypeInfo},mS:function(a,b){return a[0].builtin$cls+H.ia(a,1,b)},Ko:function(a,b){if(a==null)return"dynamic"
else if(typeof a==="object"&&a!==null&&a.constructor===Array)return H.mS(a,b)
else if(typeof a=="function")return a.builtin$cls
else if(typeof a==="number"&&Math.floor(a)===a)return C.jn.bu(a)
else return},ia:function(a,b,c){var z,y,x,w,v,u
if(a==null)return""
z=P.p9("")
for(y=b,x=!0,w=!0;y<a.length;++y){if(x)x=!1
else z.vM=z.vM+", "
v=a[y]
if(v!=null)w=!1
u=H.Ko(v,c)
u=typeof u==="string"?u:H.d(u)
z.vM=z.vM+u}return w?"":"<"+H.d(z)+">"},or:function(a){var z=$.NF
return"Instance of "+(z==null?"<Unknown>":z.call$1(a))},wz:function(a){return H.eQ(a)},iw:function(a,b,c){Object.defineProperty(a, b, {value: c, enumerable: false, writable: true, configurable: true})},w3:function(a){var z,y,x,w,v,u
z=$.NF.call$1(a)
y=$.nw[z]
if(y!=null){Object.defineProperty(a, init.dispatchPropertyName, {value: y, enumerable: false, writable: true, configurable: true})
return y.i}x=$.vv[z]
if(x!=null)return x
w=init.interceptorsByTag[z]
if(w==null){z=$.TX.call$2(a,z)
if(z!=null){y=$.nw[z]
if(y!=null){Object.defineProperty(a, init.dispatchPropertyName, {value: y, enumerable: false, writable: true, configurable: true})
return y.i}x=$.vv[z]
if(x!=null)return x
w=init.interceptorsByTag[z]}}if(w==null)return
x=w.prototype
v=z[0]
if(v==="!"){y=H.Va(x)
$.nw[z]=y
Object.defineProperty(a, init.dispatchPropertyName, {value: y, enumerable: false, writable: true, configurable: true})
return y.i}if(v==="~"){$.vv[z]=x
return x}if(v==="-"){u=H.Va(x)
Object.defineProperty(Object.getPrototypeOf(a), init.dispatchPropertyName, {value: u, enumerable: false, writable: true, configurable: true})
return u.i}if(v==="+")return H.Lc(a,x)
if(v==="*")throw H.b(P.SY(z))
if(init.leafTags[z]===true){u=H.Va(x)
Object.defineProperty(Object.getPrototypeOf(a), init.dispatchPropertyName, {value: u, enumerable: false, writable: true, configurable: true})
return u.i}else return H.Lc(a,x)},Lc:function(a,b){var z,y
z=Object.getPrototypeOf(a)
y=J.Qu(b,z,null,null)
Object.defineProperty(z, init.dispatchPropertyName, {value: y, enumerable: false, writable: true, configurable: true})
return b},Va:function(a){return J.Qu(a,!1,null,!!a.$isXj)},VF:function(a,b,c){var z=b.prototype
if(init.leafTags[a]===true)return J.Qu(z,!1,null,!!z.$isXj)
else return J.Qu(z,c,null,null)},XD:function(){if(!0===$.Bv)return
$.Bv=!0
H.Z1()},Z1:function(){var z,y,x,w,v,u,t
$.nw=Object.create(null)
$.vv=Object.create(null)
H.kO()
z=init.interceptorsByTag
y=Object.getOwnPropertyNames(z)
if(typeof window!="undefined"){window
for(x=0;x<y.length;++x){w=y[x]
v=$.x7.call$1(w)
if(v!=null){u=H.VF(w,z[w],v)
if(u!=null)Object.defineProperty(v, init.dispatchPropertyName, {value: u, enumerable: false, writable: true, configurable: true})}}}for(x=0;x<y.length;++x){w=y[x]
if(/^[A-Za-z_]/.test(w)){t=z[w]
z["!"+w]=t
z["~"+w]=t
z["-"+w]=t
z["+"+w]=t
z["*"+w]=t}}},kO:function(){var z,y,x,w,v,u,t
z=C.HX()
z=H.ud(C.Mc,H.ud(C.XQ,H.ud(C.XQ,H.ud(C.Px,H.ud(C.dE,H.ud(C.dK(C.Mo),z))))))
if(typeof dartNativeDispatchHooksTransformer!="undefined"){y=dartNativeDispatchHooksTransformer
if(typeof y=="function")y=[y]
if(y.constructor==Array)for(x=0;x<y.length;++x){w=y[x]
if(typeof w=="function")z=w(z)||z}}v=z.getTag
u=z.getUnknownTag
t=z.prototypeForTag
$.NF=new H.dC(v)
$.TX=new H.wN(u)
$.x7=new H.VX(t)},ud:function(a,b){return a(b)||b},dr:{"":"Tp;a",
call$0:function(){return this.a.call$0()}},TL:{"":"Tp;b,c",
call$0:function(){return this.b.call$1(this.c)}},KX:{"":"Tp;d,e,f",
call$0:function(){return this.d.call$2(this.e,this.f)}},uZ:{"":"Tp;g,h,i,j",
call$0:function(){return this.g.call$3(this.h,this.i,this.j)}},OQ:{"":"Tp;k,l,m,n,o",
call$0:function(){return this.k.call$4(this.l,this.m,this.n,this.o)}},Tp:{"":"a;",
bu:function(a){return"Closure"}},dC:{"":"Tp;a",
call$1:function(a){return this.a(a)}},wN:{"":"Tp;b",
call$2:function(a,b){return this.b(a,b)}},VX:{"":"Tp;c",
call$1:function(a){return this.c(a)}}}],["dart._collection.dev","dart:_collection-dev",,H,{mx:function(a,b,c){var z,y,x
for(y=0;y<$.RM().length;++y){x=$.RM()
if(y>=x.length)throw H.e(x,y)
if(x[y]===a)return H.d(b)+"..."+H.d(c)}z=P.p9("")
try{$.RM().push(a)
z.KF(b)
z.We(a,", ")
z.KF(c)}finally{x=$.RM()
if(0>=x.length)throw H.e(x,0)
x.pop()}return z.gvM()},a7:{"":"a;Kw,qn,j2,mD",
gl:function(){return this.mD},
G:function(){var z,y,x,w
z=this.Kw
y=J.U6(z)
x=y.gB(z)
if(this.qn!==x)throw H.b(P.a4(z))
w=this.j2
if(w>=x){this.mD=null
return!1}this.mD=y.Zv(z,w)
this.j2=this.j2+1
return!0}},SU:{"":"a;"}}],["dart.collection","dart:collection",,P,{jB:function(){var z=Object.create(null)
z["<non-identifier-key>"]=z
delete z["<non-identifier-key>"]
return z},yv:function(){return new P.YO(0,null,null,null,null)},FO:function(a){var z,y
y=$.xb()
if(y.tg(y,a))return"(...)"
y=$.xb()
y.h(y,a)
z=[]
try{P.Vr(a,z)}finally{y=$.xb()
y.Rz(y,a)}y=P.p9("(")
y.We(z,", ")
y.KF(")")
return y.vM},Vr:function(a,b){var z,y,x,w,v,u,t,s,r,q
z=a.gA(a)
y=0
x=0
while(!0){if(!(y<80||x<3))break
if(!z.G())return
w=H.d(z.gl())
b.push(w)
y+=w.length+2;++x}if(!z.G()){if(x<=5)return
if(0>=b.length)throw H.e(b,0)
v=b.pop()
if(0>=b.length)throw H.e(b,0)
u=b.pop()}else{t=z.gl();++x
if(!z.G()){if(x<=4){b.push(H.d(t))
return}v=H.d(t)
if(0>=b.length)throw H.e(b,0)
u=b.pop()
y+=v.length+2}else{s=z.gl();++x
for(;z.G();t=s,s=r){r=z.gl();++x
if(x>100){while(!0){if(!(y>75&&x>3))break
if(0>=b.length)throw H.e(b,0)
y-=b.pop().length+2;--x}b.push("...")
return}}u=H.d(t)
v=H.d(s)
y+=v.length+u.length+4}}if(x>b.length+2){y+=5
q="..."}else q=null
while(!0){if(!(y>80&&b.length>3))break
if(0>=b.length)throw H.e(b,0)
y-=b.pop().length+2
if(q==null){y+=5
q="..."}}if(q!=null)b.push(q)
b.push(u)
b.push(v)},jg:{"":"u3;",
gA:function(a){return new P.oz(this,this.Zl(),0,null)},
gB:function(a){return this.X5},
tg:function(a,b){var z=this.OB
if(z==null)return!1
return this.aH(z[this.nm(b)],b)>=0},
h:function(a,b){var z,y,x
z=this.OB
if(z==null){z=P.jB()
this.OB=z}y=this.nm(b)
x=z[y]
if(x==null)z[y]=[b]
else{if(this.aH(x,b)>=0)return!1
x.push(b)}this.X5=this.X5+1
this.DM=null
return!0},
Rz:function(a,b){var z,y,x
z=this.OB
if(z==null)return!1
y=z[this.nm(b)]
x=this.aH(y,b)
if(x<0)return!1
this.X5=this.X5-1
this.DM=null
y.splice(x,1)
return!0},
Zl:function(){var z,y,x,w,v,u,t,s,r,q,p,o
z=this.DM
if(z!=null)return z
y=P.A(this.X5)
x=this.vv
if(x!=null){w=Object.getOwnPropertyNames(x)
v=w.length
for(u=0,t=0;t<v;++t){y[u]=w[t];++u}}else u=0
s=this.OX
if(s!=null){w=Object.getOwnPropertyNames(s)
v=w.length
for(t=0;t<v;++t){y[u]=+w[t];++u}}r=this.OB
if(r!=null){w=Object.getOwnPropertyNames(r)
v=w.length
for(t=0;t<v;++t){q=r[w[t]]
p=q.length
for(o=0;o<p;++o){y[u]=q[o];++u}}}this.DM=y
return y},
nm:function(a){return J.v1(a)&0x3ffffff},
aH:function(a,b){var z,y
if(a==null)return-1
z=a.length
for(y=0;y<z;++y)if(J.xC(a[y],b))return y
return-1}},YO:{"":"jg;X5,vv,OX,OB,DM",
nm:function(a){return H.CU(a)&0x3ffffff},
aH:function(a,b){var z,y
if(a==null)return-1
z=a.length
for(y=0;y<z;++y)if(a[y]===b)return y
return-1}},oz:{"":"a;O2,DM,zi,fD",
gl:function(){return this.fD},
G:function(){var z,y,x
z=this.DM
y=this.zi
x=this.O2
if(z!==x.DM)throw H.b(P.a4(x))
else if(y>=z.length){this.fD=null
return!1}else{this.fD=z[y]
this.zi=y+1
return!0}}},u3:{"":"mW;",
bu:function(a){return H.mx(this,"{","}")}},mW:{"":"a;",
gB:function(a){var z,y
z=this.gA(this)
for(y=0;z.G();)++y
return y},
Zv:function(a,b){var z,y,x
if(b<0)throw H.b(P.N(b))
for(z=this.gA(this),y=b;z.G();){x=z.gl()
if(y===0)return x;--y}throw H.b(P.N(b))},
bu:function(a){return P.FO(this)}},lD:{"":"a;",
gA:function(a){return new H.a7(a,this.gB(a),0,null)},
Zv:function(a,b){return this.t(a,b)},
bu:function(a){var z,y
y=$.xb()
if(y.tg(y,a))return"[...]"
z=P.p9("")
try{y=$.xb()
y.h(y,a)
z.KF("[")
z.We(a,", ")
z.KF("]")}finally{y=$.xb()
y.Rz(y,a)}return z.gvM()}}}],["dart.core","dart:core",,P,{hl:function(a){return H.o9(a)},FM:function(a){return new P.HG(a)},A:function(a){if(a==null)return new Array(0)
if(typeof a!=="number"||Math.floor(a)!==a||a<0)throw H.b(P.u("Length must be a positive integer: "+H.d(a)+"."))
return H.rD(a)},Ge:{"":"a;"},LK:{"":"Ge;",
bu:function(a){return"Throw of null."}},AT:{"":"Ge;G1",
bu:function(a){var z=this.G1
if(z!=null)return"Illegal argument(s): "+H.d(z)
return"Illegal argument(s)"},
static:{u:function(a){return new P.AT(a)}}},bJ:{"":"AT;G1",
bu:function(a){return"RangeError: "+H.d(this.G1)},
static:{N:function(a){return new P.bJ("value "+H.d(a))},TE:function(a,b,c){return new P.bJ("value "+H.d(a)+" not in range "+b+".."+H.d(c))}}},ds:{"":"Ge;G1",
bu:function(a){var z=this.G1
return z!=null?"UnimplementedError: "+H.d(z):"UnimplementedError"},
static:{SY:function(a){return new P.ds(a)}}},UV:{"":"Ge;YA",
bu:function(a){return"Concurrent modification during iteration: "+P.hl(this.YA)+"."},
static:{a4:function(a){return new P.UV(a)}}},t7:{"":"Ge;Wo",
bu:function(a){return"Reading static variable '"+this.Wo+"' during its initialization"},
static:{Gz:function(a){return new P.t7(a)}}},HG:{"":"a;G1",
bu:function(a){return"Exception: "+this.G1}},c8:{"":"a;",
bu:function(a){return"null"}},a:{"":";",
n:function(a,b){return this===b},
giO:function(a){return H.eQ(this)},
bu:function(a){return H.o9(this)}},Rn:{"":"a;vM<",
gB:function(a){return this.vM.length},
KF:function(a){var z=typeof a==="string"?a:H.d(a)
this.vM=this.vM+z},
We:function(a,b){var z,y
z=J.GP(a)
if(!z.G())return
if(b.length===0)do{y=z.gl()
y=typeof y==="string"?y:H.d(y)
this.vM=this.vM+y}while(z.G())
else{this.KF(z.gl())
for(;z.G();){this.vM=this.vM+b
y=z.gl()
y=typeof y==="string"?y:H.d(y)
this.vM=this.vM+y}}},
bu:function(a){return this.vM},
PD:function(a){this.vM=a},
static:{p9:function(a){var z=new P.Rn("")
z.PD(a)
return z}}}}],["dart.dom.html","dart:html",,W,{qE:{"":"cv;","%":"HTMLAppletElement|HTMLAreaElement|HTMLAudioElement|HTMLBRElement|HTMLBaseElement|HTMLBaseFontElement|HTMLBodyElement|HTMLButtonElement|HTMLContentElement|HTMLDListElement|HTMLDataListElement|HTMLDetailsElement|HTMLDialogElement|HTMLDirectoryElement|HTMLDivElement|HTMLEmbedElement|HTMLFieldSetElement|HTMLFontElement|HTMLFrameElement|HTMLFrameSetElement|HTMLHRElement|HTMLHeadElement|HTMLHeadingElement|HTMLHtmlElement|HTMLIFrameElement|HTMLImageElement|HTMLInputElement|HTMLKeygenElement|HTMLLIElement|HTMLLabelElement|HTMLLegendElement|HTMLLinkElement|HTMLMapElement|HTMLMarqueeElement|HTMLMediaElement|HTMLMenuElement|HTMLMetaElement|HTMLMeterElement|HTMLModElement|HTMLOListElement|HTMLObjectElement|HTMLOptGroupElement|HTMLOptionElement|HTMLOutputElement|HTMLParagraphElement|HTMLParamElement|HTMLPreElement|HTMLProgressElement|HTMLQuoteElement|HTMLScriptElement|HTMLShadowElement|HTMLSourceElement|HTMLSpanElement|HTMLStyleElement|HTMLTableCaptionElement|HTMLTableCellElement|HTMLTableColElement|HTMLTableDataCellElement|HTMLTableElement|HTMLTableHeaderCellElement|HTMLTableRowElement|HTMLTableSectionElement|HTMLTemplateElement|HTMLTextAreaElement|HTMLTitleElement|HTMLTrackElement|HTMLUListElement|HTMLUnknownElement|HTMLVideoElement;HTMLElement"},Gh:{"":"qE;",
bu:function(a){return a.toString()},
"%":"HTMLAnchorElement"},Ny:{"":"qE;",
eW:function(a,b,c){return a.getContext(b)},
Bf:function(a,b){return this.eW(a,b,null)},
"%":"HTMLCanvasElement"},Y5:{"":"Gv;","%":"CanvasRenderingContext2D;CanvasRenderingContext"},Nh:{"":"Gv;",
bu:function(a){return a.toString()},
"%":"DOMException"},cv:{"":"KV;",
bu:function(a){return a.localName},
"%":"SVGAElement|SVGAltGlyphDefElement|SVGAltGlyphElement|SVGAltGlyphItemElement|SVGAnimateColorElement|SVGAnimateElement|SVGAnimateMotionElement|SVGAnimateTransformElement|SVGAnimationElement|SVGCircleElement|SVGClipPathElement|SVGComponentTransferFunctionElement|SVGCursorElement|SVGDefsElement|SVGDescElement|SVGElement|SVGEllipseElement|SVGFEBlendElement|SVGFEColorMatrixElement|SVGFEComponentTransferElement|SVGFECompositeElement|SVGFEConvolveMatrixElement|SVGFEDiffuseLightingElement|SVGFEDisplacementMapElement|SVGFEDistantLightElement|SVGFEDropShadowElement|SVGFEFloodElement|SVGFEFuncAElement|SVGFEFuncBElement|SVGFEFuncGElement|SVGFEFuncRElement|SVGFEGaussianBlurElement|SVGFEImageElement|SVGFEMergeElement|SVGFEMergeNodeElement|SVGFEMorphologyElement|SVGFEOffsetElement|SVGFEPointLightElement|SVGFESpecularLightingElement|SVGFESpotLightElement|SVGFETileElement|SVGFETurbulenceElement|SVGFilterElement|SVGFontElement|SVGFontFaceElement|SVGFontFaceFormatElement|SVGFontFaceNameElement|SVGFontFaceSrcElement|SVGFontFaceUriElement|SVGForeignObjectElement|SVGGElement|SVGGlyphElement|SVGGlyphRefElement|SVGGradientElement|SVGGraphicsElement|SVGHKernElement|SVGImageElement|SVGLineElement|SVGLinearGradientElement|SVGMPathElement|SVGMarkerElement|SVGMaskElement|SVGMetadataElement|SVGMissingGlyphElement|SVGPathElement|SVGPatternElement|SVGPolygonElement|SVGPolylineElement|SVGRadialGradientElement|SVGRectElement|SVGSVGElement|SVGScriptElement|SVGSetElement|SVGStopElement|SVGStyleElement|SVGSwitchElement|SVGSymbolElement|SVGTSpanElement|SVGTextContentElement|SVGTextElement|SVGTextPathElement|SVGTextPositioningElement|SVGTitleElement|SVGUseElement|SVGVKernElement|SVGViewElement;Element"},D0:{"":"Gv;","%":";EventTarget"},Yu:{"":"qE;B:length=","%":"HTMLFormElement"},KV:{"":"D0;",
bu:function(a){var z=a.nodeValue
return z==null?J.Gv.prototype.bu.call(this,a):z},
"%":"Document|HTMLDocument;Node"},lp:{"":"qE;B:length=","%":"HTMLSelectElement"},K5:{"":"D0;",
bu:function(a){return a.toString()},
"%":"DOMWindow|Window"},Ij:{"":"ec;",
gB:function(a){return a.length},
t:function(a,b){var z=a.length
if(b>>>0!==b||b>=z)throw H.b(P.TE(b,0,z))
return a[b]},
Zv:function(a,b){if(b<0||b>=a.length)throw H.e(a,b)
return a[b]},
$isXj:true,
"%":"GamepadList"},RA:{"":"Gv+lD;"},ec:{"":"RA+Gm;"},Gm:{"":"a;",
gA:function(a){return W.yB(a)}},W9:{"":"a;nj,vN,Nq,QZ",
G:function(){var z,y
z=this.Nq+1
y=this.vN
if(z<y){this.QZ=J.UQ(this.nj,z)
this.Nq=z
return!0}this.QZ=null
this.Nq=y
return!1},
gl:function(){return this.QZ},
static:{yB:function(a){return new W.W9(a,J.q8(a),-1,null)}}}}],["dart.dom.web_gl","dart:web_gl",,P,{Jo:{"":"Y5;",
v3:function(a,b,c){return a.attachShader(b,c)},
Ug:function(a,b,c){return a.bindBuffer(b,c)},
Vl:function(a,b,c,d){return a.bufferData(b,c,d)},
Sl:function(a,b){return a.clear(b)},
kd:function(a,b,c,d,e){return a.clearColor(b,c,d,e)},
jV:function(a,b){return a.compileShader(b)},
Gp:function(a){return a.createBuffer()},
pC:function(a){return a.createProgram()},
WV:function(a,b){return a.createShader(b)},
rn:function(a,b,c,d,e){return a.drawElements(b,c,d,e)},
Qc:function(a,b){return a.enable(b)},
CF:function(a,b){return a.enableVertexAttribArray(b)},
ci:function(a,b,c){return a.getAttribLocation(b,c)},
D7:function(a,b,c){return a.getProgramParameter(b,c)},
yF:function(a,b){return a.getShaderInfoLog(b)},
p6:function(a,b,c){return a.getShaderParameter(b,c)},
YE:function(a,b,c){return a.getUniformLocation(b,c)},
Ev:function(a,b){return a.linkProgram(b)},
Yw:function(a,b,c){return a.shaderSource(b,c)},
vL:function(a,b,c){return a.uniform4fv(b,c)},
d2:function(a,b,c,d){return a.uniformMatrix4fv(b,c,d)},
nA:function(a,b){return a.useProgram(b)},
l6:function(a,b,c,d,e,f,g){return a.vertexAttribPointer(b,c,d,e,f,g)},
fw:function(a,b,c,d,e){return a.viewport(b,c,d,e)},
"%":"WebGLRenderingContext"}}],["dart.typed_data","dart:typed_data",,P,{AS:{"":"Gv;",
aq:function(a,b,c){if(b<0||b>=c)throw H.b(P.TE(b,0,c))
else throw H.b(P.u("Invalid list index "+b))},
"%":";ArrayBufferView;xG|Vj|VW|RK"},oI:{"":"Vj;",
gB:function(a){return C.i7(a)},
t:function(a,b){var z=C.i7(a)
if(b>>>0!=b||b>=z)this.aq(a,b,z)
return a[b]},
$isXj:true,
"%":"Float32Array"},rF:{"":"RK;",
gB:function(a){return C.i7(a)},
t:function(a,b){var z=C.i7(a)
if(b>>>0!=b||b>=z)this.aq(a,b,z)
return a[b]},
$isXj:true,
"%":"Int16Array"},xG:{"":"AS+lD;"},Vj:{"":"xG+SU;"},VW:{"":"AS+lD;"},RK:{"":"VW+SU;"}}],["","file:///C:/Users/colsen/dart/game/web/game.dart",,D,{wT:function(a,b,c,d){var z,y
z=1/Math.tan(0.5*a*3.141592653589793/180)
y=1/(c-d)
return[z/b,0,0,0,0,z,0,0,0,0,(c+d)*y,-1,0,0,c*d*y*2,0]},nA:function(a,b){var z,y,x,w,v
z=Math.cos(-1.0471975511965976)
y=Math.sin(-1.0471975511965976)
x=Math.cos(0.7853981633974483)
w=Math.sin(0.7853981633974483)
v=-y
return[x,z*w,y*w,0,w,-z*x,v*x,0,0,v,z,0,a*x+b*w,-(-a*z*w+b*z*x),a*y*w+-b*y*x-256,1]},nd:function(a){var z,y
$.cy=J.Rw($.Wy)
J.wY($.Wy,34962,$.cy)
z=-a
y=$.Wy
z=new Float32Array([z,z,0,z,a,0,a,z,0,a,a,0])
z.$dartCachedLength=z.length
J.Fe(y,34962,z,35044)},pB:function(a){var z,y,x
$.Lp=J.Rw($.Wy)
J.wY($.Wy,34962,$.Lp)
z=-a
y=1.62*a
x=$.Wy
y=new Float32Array([z,z,y,1,a,z,y,1,a,a,y,1,z,z,0,0.25,a,z,0,0,a,a,0,0.25,z,z,0,1,a,z,0,0.25,a,a,0,1,a,z,0,1,z,a,0,1,a,z,y,0.25])
y.$dartCachedLength=y.length
J.Fe(x,34962,y,35044)
$.ah=J.Rw($.Wy)
J.wY($.Wy,34963,$.ah)
y=$.Wy
x=new Int16Array([0,11,4,0,4,3,11,2,4,4,2,5,3,4,10,10,4,5])
x.$dartCachedLength=x.length
J.Fe(y,34963,x,35044)
$.uC=J.Rw($.Wy)
J.wY($.Wy,34963,$.uC)
x=$.Wy
y=new Int16Array([0,1,3,3,1,7,3,7,8,3,8,10])
y.$dartCachedLength=y.length
J.Fe(x,34963,y,35044)
$.PE=J.Rw($.Wy)
J.wY($.Wy,34963,$.PE)
y=$.Wy
x=new Int16Array([1,2,5,1,5,7,6,7,5,6,5,10])
x.$dartCachedLength=x.length
J.Fe(y,34963,x,35044)
$.NU=J.Rw($.Wy)
J.wY($.Wy,34963,$.NU)
x=$.Wy
y=new Int16Array([6,9,8,6,8,10])
y.$dartCachedLength=y.length
J.Fe(x,34963,y,35044)},Pt:function(a){var z,y,x
$.BQ=J.Rw($.Wy)
J.wY($.Wy,34962,$.BQ)
z=-a
y=1.62*a
x=$.Wy
y=new Float32Array([a,z,0,0,a,z,y,1,z,z,0,0,z,z,y,1])
y.$dartCachedLength=y.length
J.Fe(x,34962,y,35044)},Xg:function(a){var z,y,x
$.zj=J.Rw($.Wy)
J.wY($.Wy,34962,$.zj)
z=-a
y=1.62*a
x=$.Wy
y=new Float32Array([a,z,0,0,a,z,y,1,a,a,0,0,a,a,y,1])
y.$dartCachedLength=y.length
J.Fe(x,34962,y,35044)},ks:function(a){var z,y
$.ko=J.Rw($.Wy)
J.wY($.Wy,34962,$.ko)
z=-a
y=$.Wy
z=new Float32Array([z,z,0,a,z,0,a,z,0,a,z,-1.62*a,a,z,0,a,a,0])
z.$dartCachedLength=z.length
J.Fe(y,34962,z,35044)},ze:function(){J.wY($.Wy,34962,$.Lp)
J.wY($.Wy,34963,$.NU)
J.GB($.Wy,$.PS,4,5126,!1,0,0)
J.Hb($.Wy,4,6,5123,0)},pY:function(){J.wY($.Wy,34962,$.Lp)
J.wY($.Wy,34963,$.ah)
J.GB($.Wy,$.PS,4,5126,!1,0,0)
J.Hb($.Wy,4,18,5123,0)},cJ:function(){J.wY($.Wy,34962,$.Lp)
J.wY($.Wy,34963,$.uC)
J.GB($.Wy,$.PS,4,5126,!1,0,0)
J.Hb($.Wy,4,12,5123,0)},mz:function(){J.wY($.Wy,34962,$.Lp)
J.wY($.Wy,34963,$.PE)
J.GB($.Wy,$.PS,4,5126,!1,0,0)
J.Hb($.Wy,4,12,5123,0)},E2:function(){var z,y,x,w,v,u,t,s,r,q,p,o,n,m,l,k,j,i,h,g
window.navigator.webkitGetGamepads()
z=document.querySelector("#glcanvas")
$.Wy=J.PB(z,"experimental-webgl")
J.Np($.Wy,0,0,0,1)
J.aS($.Wy,2929)
D.nd(32)
D.Pt(32)
D.Xg(32)
D.ks(32)
D.pB(32)
y=J.lA($.Wy,35633)
J.Rb($.Wy,y,"    precision highp float;\n    attribute vec4 aVertexPosition;\n\n    uniform mat4 uMVMatrix;\n    uniform mat4 uPMatrix;\n    varying vec3 position;\n\n    void main(void) {\n      position = aVertexPosition.xyz;\n      gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition.xyz, 1.0);\n    }\n  ")
J.Ef($.Wy,y)
if(J.cN($.Wy,y,35713)!==!0){window.alert(J.zO($.Wy,y))
return}x=J.lA($.Wy,35632)
J.Rb($.Wy,x,"    #define M_PI 3.1415926535897932384626433832795\n    precision highp float;\n    uniform vec4 color;\n    uniform vec4 ambientOcclusion;  // occlusion factor for each dimension.\n    varying vec3 position;\n\n    void main(void) {\n      vec4 ao = vec4(\n        0.5 * (1.0 + sin((position.y+32.0)/64.0 * M_PI / 2.0)),\n        0.5 * (1.0 + sin((-position.x+32.0)/64.0 * M_PI / 2.0)),\n        (1.0 + sin((position.z)/(1.62*32.0) * M_PI / 2.0)),\n        1.0);\n      ao = mix(vec4(1.0), ao, ambientOcclusion);\n      ao = pow(ao, vec4(1.25));\n      //gl_FragColor = color * vec4(vec3(mix(1.0, pow(ao.x, 1.2), ambientOcclusion.x)*mix(1.0, pow(ao.y, 1.2), ambientOcclusion.y)), 1.0);\n      gl_FragColor = color * vec4(vec3(ao.x*ao.y*ao.z), 1.0);\n    }\n  ")
J.Ef($.Wy,x)
if(J.cN($.Wy,x,35713)!==!0){window.alert(J.zO($.Wy,x))
return}w=J.WG($.Wy)
J.to($.Wy,w,y)
J.to($.Wy,w,x)
J.au($.Wy,w)
if(J.U3($.Wy,w,35714)!==!0)window.alert("Could not initialise shaders")
$.PS=J.E4($.Wy,w,"aVertexPosition")
J.Oo($.Wy,$.PS)
v=J.a5($.Wy,w,"uPMatrix")
u=J.a5($.Wy,w,"uMVMatrix")
t=J.a5($.Wy,w,"color")
s=J.a5($.Wy,w,"ambientOcclusion")
J.N6($.Wy,0,0,z.width,z.height)
J.Iz($.Wy,16640)
r=z.width
q=z.height
if(typeof r!=="number")throw r.V()
if(typeof q!=="number")throw H.s(q)
p=D.wT(60,r/q,0.1,1000)
J.jO($.Wy,w)
q=$.Wy
r=new Float32Array(p)
r.$dartCachedLength=r.length
J.pL(q,v,!1,r)
for(o=null,n=0;$.Lv(),n<8;++n)for(r=n-1,q=r>=0,m=n*64,l=0;l<$.Lv()[n].length;++l){k=$.Lv()[n]
if(l>=k.length)throw H.e(k,l)
if(J.xC(k[l],0))continue
o=D.nA(l*64-128,m)
if(q){k=$.Lv()
if(r<0)throw H.e(k,r)
k=k[r]
if(l>=k.length)throw H.e(k,l)
j=J.xC(k[l],0)}else j=!0
k=l+1
if(k<$.Lv()[n].length){i=$.Lv()[n]
if(k>=i.length)throw H.e(i,k)
h=J.xC(i[k],0)}else h=!0
if(j&&h){k=$.Wy
i=$.It()
g=$.Lv()[n]
if(l>=g.length)throw H.e(g,l)
g=g[l]
if(g>>>0!==g||g>=5)throw H.e(i,g)
g=new Float32Array(i[g])
g.$dartCachedLength=g.length
J.vt(k,t,g)
g=$.Wy
k=new Float32Array([1,1,1,0])
k.$dartCachedLength=k.length
J.vt(g,s,k)
k=$.Wy
g=new Float32Array(o)
g.$dartCachedLength=g.length
J.pL(k,u,!1,g)
D.pY()}else if(j){k=$.Wy
i=$.It()
g=$.Lv()[n]
if(l>=g.length)throw H.e(g,l)
g=g[l]
if(g>>>0!==g||g>=5)throw H.e(i,g)
g=new Float32Array(i[g])
g.$dartCachedLength=g.length
J.vt(k,t,g)
g=$.Wy
k=new Float32Array([1,0,1,0])
k.$dartCachedLength=k.length
J.vt(g,s,k)
k=$.Wy
g=new Float32Array(o)
g.$dartCachedLength=g.length
J.pL(k,u,!1,g)
D.cJ()}else{k=$.Wy
if(h){i=$.It()
g=$.Lv()[n]
if(l>=g.length)throw H.e(g,l)
g=g[l]
if(g>>>0!==g||g>=5)throw H.e(i,g)
g=new Float32Array(i[g])
g.$dartCachedLength=g.length
J.vt(k,t,g)
g=$.Wy
k=new Float32Array([0,1,1,0])
k.$dartCachedLength=k.length
J.vt(g,s,k)
k=$.Wy
g=new Float32Array(o)
g.$dartCachedLength=g.length
J.pL(k,u,!1,g)
D.mz()}else{i=$.It()
g=$.Lv()[n]
if(l>=g.length)throw H.e(g,l)
g=g[l]
if(g>>>0!==g||g>=5)throw H.e(i,g)
g=new Float32Array(i[g])
g.$dartCachedLength=g.length
J.vt(k,t,g)
g=$.Wy
k=new Float32Array([0,0,1,0])
k.$dartCachedLength=k.length
J.vt(g,s,k)
k=$.Wy
g=new Float32Array(o)
g.$dartCachedLength=g.length
J.pL(k,u,!1,g)
D.ze()}}}}},1],])
I.$finishClasses($$,$,null)
$$=null
init.globalFunctions.Eu=H.Eu=new H.yh(H.Ju,"Eu")
init.globalFunctions.eH=H.eH=new H.Pz(H.ft,"eH")
J.RE=function(a){if(a==null)return a
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.M3(a)}
J.U6=function(a){if(typeof a=="string")return J.O.prototype
if(a==null)return a
if(a.constructor==Array)return J.Q.prototype
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.M3(a)}
J.rY=function(a){if(typeof a=="string")return J.O.prototype
if(a==null)return a
if(!(a instanceof P.a))return J.is.prototype
return a}
J.w1=function(a){if(a==null)return a
if(a.constructor==Array)return J.Q.prototype
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.M3(a)}
J.x=function(a){if(typeof a=="number"){if(Math.floor(a)==a)return J.im.prototype
return J.VA.prototype}if(typeof a=="string")return J.O.prototype
if(a==null)return J.CD.prototype
if(typeof a=="boolean")return J.yE.prototype
if(a.constructor==Array)return J.Q.prototype
if(typeof a!="object")return a
if(a instanceof P.a)return a
return J.M3(a)}
C.jn=J.im.prototype
C.xB=J.O.prototype
C.Mc=function(hooks) {
  if (typeof dartExperimentalFixupGetTag != "function") return hooks;
  hooks.getTag = dartExperimentalFixupGetTag(hooks.getTag);
}
C.dE=function(hooks) {
  var userAgent = typeof navigator == "object" ? navigator.userAgent : "";
  if (userAgent.indexOf("Firefox") == -1) return hooks;
  var getTag = hooks.getTag;
  var quickMap = {
    "BeforeUnloadEvent": "Event",
    "DataTransfer": "Clipboard",
    "GeoGeolocation": "Geolocation",
    "WorkerMessageEvent": "MessageEvent",
    "XMLDocument": "Document"};
  function getTagFirefox(o) {
    var tag = getTag(o);
    return quickMap[tag] || tag;
  }
  hooks.getTag = getTagFirefox;
}
C.Mo=function getTagFallback(o) {
  if (o == null) return "Null";
  var constructor = o.constructor;
  if (typeof constructor == "function") {
    var name = constructor.builtin$cls;
    if (typeof name == "string") return name;
    name = constructor.name;
    if (typeof name == "string"
        && name !== ""
        && name !== "Object"
        && name !== "Function.prototype") {
      return name;
    }
  }
  var s = Object.prototype.toString.call(o);
  return s.substring(8, s.length - 1);
}
C.dK=function(getTagFallback) {
  return function(hooks) {
    if (typeof navigator != "object") return hooks;
    var userAgent = navigator.userAgent;
    if (userAgent.indexOf("Chrome") >= 0 ||
        userAgent.indexOf("DumpRenderTree") >= 0) {
      return hooks;
    }
    hooks.getTag = getTagFallback;
  };
}
C.XQ=function(hooks) { return hooks; }

C.HX=function() {
  function typeNameInChrome(obj) { return obj.constructor.name; }
  function getUnknownTag(object, tag) {
    if (/^HTML[A-Z].*Element$/.test(tag)) {
      var name = Object.prototype.toString.call(object);
      if (name == "[object Object]") return null;
      return "HTMLElement";
    }
  }
  function getUnknownTagGenericBrowser(object, tag) {
    if (object instanceof HTMLElement) return "HTMLElement";
    return getUnknownTag(object, tag);
  }
  function prototypeForTag(tag) {
    if (typeof window == "undefined") return null;
    if (typeof window[tag] == "undefined") return null;
    var constructor = window[tag];
    if (typeof constructor != "function") return null;
    return constructor.prototype;
  }
  function discriminator(tag) { return null; }
  var isBrowser = typeof navigator == "object";
  return {
    getTag: typeNameInChrome,
    getUnknownTag: isBrowser ? getUnknownTagGenericBrowser : getUnknownTag,
    prototypeForTag: prototypeForTag,
    discriminator: discriminator };
}
C.i7=    ((typeof version == "function" && typeof os == "object" && "system" in os)
    || (typeof navigator == "object"
        && navigator.userAgent.indexOf('Chrome') != -1))
        ? function(x) { return x.$dartCachedLength || x.length; }
        : function(x) { return x.length; };

C.Px=function(hooks) {
  var userAgent = typeof navigator == "object" ? navigator.userAgent : "";
  if (userAgent.indexOf("Trident/") == -1) return hooks;
  var getTag = hooks.getTag;
  var quickMap = {
    "BeforeUnloadEvent": "Event",
    "DataTransfer": "Clipboard",
    "HTMLDDElement": "HTMLElement",
    "HTMLDTElement": "HTMLElement",
    "HTMLPhraseElement": "HTMLElement",
    "Position": "Geoposition"
  };
  function getTagIE(o) {
    var tag = getTag(o);
    var newTag = quickMap[tag];
    if (newTag) return newTag;
    if (tag == "Document") {
      if (!!o.xmlVersion) return "!Document";
      return "!HTMLDocument";
    }
    if (tag == "Object") {
      if (window.DataView && (o instanceof window.DataView)) return "DataView";
    }
    return tag;
  }
  function prototypeForTagIE(tag) {
    if (tag == "Document") return null;
    var constructor = window[tag];
    if (constructor == null) return null;
    return constructor.prototype;
  }
  hooks.getTag = getTagIE;
  hooks.prototypeForTag = prototypeForTagIE;
}
C.vB=J.is.prototype
$.NF=null
$.TX=null
$.x7=null
$.nw=null
$.vv=null
$.Bv=null
$.Wy=null
$.PS=null
$.cy=null
$.Lp=null
$.ah=null
$.uC=null
$.PE=null
$.NU=null
$.BQ=null
$.zj=null
$.ko=null
J.AG=function(a){return J.x(a).bu(a)}
J.E4=function(a,b,c){return J.RE(a).ci(a,b,c)}
J.Ef=function(a,b){return J.RE(a).jV(a,b)}
J.Fe=function(a,b,c,d){return J.RE(a).Vl(a,b,c,d)}
J.GB=function(a,b,c,d,e,f,g){return J.RE(a).l6(a,b,c,d,e,f,g)}
J.GP=function(a){return J.w1(a).gA(a)}
J.Hb=function(a,b,c,d,e){return J.RE(a).rn(a,b,c,d,e)}
J.Iz=function(a,b){return J.w1(a).Sl(a,b)}
J.N6=function(a,b,c,d,e){return J.RE(a).fw(a,b,c,d,e)}
J.Np=function(a,b,c,d,e){return J.RE(a).kd(a,b,c,d,e)}
J.Oo=function(a,b){return J.RE(a).CF(a,b)}
J.PB=function(a,b){return J.RE(a).Bf(a,b)}
J.Rb=function(a,b,c){return J.RE(a).Yw(a,b,c)}
J.Rw=function(a){return J.RE(a).Gp(a)}
J.U3=function(a,b,c){return J.RE(a).D7(a,b,c)}
J.UQ=function(a,b){if(a.constructor==Array||typeof a=="string"||H.wV(a,a[init.dispatchPropertyName]))if(b>>>0===b&&b<a.length)return a[b]
return J.U6(a).t(a,b)}
J.WG=function(a){return J.RE(a).pC(a)}
J.a5=function(a,b,c){return J.RE(a).YE(a,b,c)}
J.aS=function(a,b){return J.RE(a).Qc(a,b)}
J.au=function(a,b){return J.RE(a).Ev(a,b)}
J.cN=function(a,b,c){return J.RE(a).p6(a,b,c)}
J.jO=function(a,b){return J.RE(a).nA(a,b)}
J.lA=function(a,b){return J.RE(a).WV(a,b)}
J.pL=function(a,b,c,d){return J.RE(a).d2(a,b,c,d)}
J.q8=function(a){return J.U6(a).gB(a)}
J.to=function(a,b,c){return J.RE(a).v3(a,b,c)}
J.v1=function(a){return J.x(a).giO(a)}
J.vt=function(a,b,c){return J.RE(a).vL(a,b,c)}
J.wY=function(a,b,c){return J.RE(a).Ug(a,b,c)}
J.xC=function(a,b){if(a==null)return b==null
if(typeof a!="object")return b!=null&&a===b
return J.x(a).n(a,b)}
J.zO=function(a,b){return J.RE(a).yF(a,b)}
I.$lazy($,"_toStringList","Ml","RM",function(){return P.A(null)})
I.$lazy($,"_toStringVisiting","xg","xb",function(){return P.yv()})
I.$lazy($,"map","Ir","Lv",function(){return[[4,2,0,2,4,0,0,0],[3,1,1,2,4,0,0,0],[0,0,0,2,1,1,4,0],[0,0,0,0,1,1,1,1],[0,0,0,0,1,1,1,1],[0,3,3,0,0,0,0,1],[0,3,3,0,0,0,0,1],[0,0,0,0,0,0,0,1]]})
I.$lazy($,"colors","MY","It",function(){return[[0,0,0,1],[1,0,0,1],[0,1,0,1],[0,0,1,1],[1,1,1,1]]})

init.functionAliases={}
init.metadata=[];$=null
I = I.$finishIsolateConstructor(I)
$=new I()
function convertToFastObject(properties) {
  function MyClass() {};
  MyClass.prototype = properties;
  new MyClass();
  return properties;
}
A = convertToFastObject(A)
B = convertToFastObject(B)
C = convertToFastObject(C)
D = convertToFastObject(D)
E = convertToFastObject(E)
F = convertToFastObject(F)
G = convertToFastObject(G)
H = convertToFastObject(H)
J = convertToFastObject(J)
K = convertToFastObject(K)
L = convertToFastObject(L)
M = convertToFastObject(M)
N = convertToFastObject(N)
O = convertToFastObject(O)
P = convertToFastObject(P)
Q = convertToFastObject(Q)
R = convertToFastObject(R)
S = convertToFastObject(S)
T = convertToFastObject(T)
U = convertToFastObject(U)
V = convertToFastObject(V)
W = convertToFastObject(W)
X = convertToFastObject(X)
Y = convertToFastObject(Y)
Z = convertToFastObject(Z)
!function(){var z=Object.prototype
for(var y=0;;y++){var x="___dart_dispatch_record_ZxYxX_0_"
if(y>0)x=rootProperty+"_"+y
if(!(x in z))return init.dispatchPropertyName=x}}()
;(function (callback) {
  if (typeof document === "undefined") {
    callback(null);
    return;
  }
  if (document.currentScript) {
    callback(document.currentScript);
    return;
  }

  var scripts = document.scripts;
  function onLoad(event) {
    for (var i = 0; i < scripts.length; ++i) {
      scripts[i].removeEventListener("load", onLoad, false);
    }
    callback(event.target);
  }
  for (var i = 0; i < scripts.length; ++i) {
    scripts[i].addEventListener("load", onLoad, false);
  }
})(function(currentScript) {
  init.currentScript = currentScript;

  if (typeof dartMainRunner === "function") {
    dartMainRunner(function() { D.E2(); });
  } else {
    D.E2();
  }
})
function init(){I.p={}
function generateAccessor(a,b,c){var y=a.length
var x=a.charCodeAt(y-1)
var w=false
if(x==45){y--
x=a.charCodeAt(y-1)
a=a.substring(0,y)
w=true}x=x>=60&&x<=64?x-59:x>=123&&x<=126?x-117:x>=37&&x<=43?x-27:0
if(x){var v=x&3
var u=x>>2
var t=a=a.substring(0,y-1)
var s=a.indexOf(":")
if(s>0){t=a.substring(0,s)
a=a.substring(s+1)}if(v){var r=v&2?"r":""
var q=v&1?"this":"r"
var p="return "+q+"."+a
var o=c+".prototype.g"+t+"="
var n="function("+r+"){"+p+"}"
if(w)b.push(o+"$reflectable("+n+");\n")
else b.push(o+n+";\n")}if(u){var r=u&2?"r,v":"v"
var q=u&1?"this":"r"
var p=q+"."+a+"=v"
var o=c+".prototype.s"+t+"="
var n="function("+r+"){"+p+"}"
if(w)b.push(o+"$reflectable("+n+");\n")
else b.push(o+n+";\n")}}return a}I.p.$generateAccessor=generateAccessor
function defineClass(a,b,c){var y=[]
var x="function "+b+"("
var w=""
for(var v=0;v<c.length;v++){if(v!=0)x+=", "
var u=generateAccessor(c[v],y,b)
var t="parameter_"+u
x+=t
w+="this."+u+" = "+t+";\n"}x+=") {\n"+w+"}\n"
x+=b+".builtin$cls=\""+a+"\";\n"
x+="$desc=$collectedClasses."+b+";\n"
x+="if($desc instanceof Array) $desc = $desc[1];\n"
x+=b+".prototype = $desc;\n"
if(typeof defineClass.name!="string"){x+=b+".name=\""+b+"\";\n"}x+=y.join("")
return x}var z=function(){function tmp(){}var y=Object.prototype.hasOwnProperty
return function(a,b){tmp.prototype=b.prototype
var x=new tmp()
var w=a.prototype
for(var v in w)if(y.call(w,v))x[v]=w[v]
x.constructor=a
a.prototype=x
return x}}()
I.$finishClasses=function(a,b,c){var y={}
if(!init.allClasses)init.allClasses={}
var x=init.allClasses
var w=Object.prototype.hasOwnProperty
if(typeof dart_precompiled=="function"){var v=dart_precompiled(a)}else{var u="function $reflectable(fn){fn.$reflectable=1;return fn};\n"+"var $desc;\n"
var t=[]}for(var s in a){if(w.call(a,s)){var r=a[s]
if(r instanceof Array)r=r[1]
var q=r[""],p,o=s,n=q
if(typeof q=="string"){var m=q.split("/")
if(m.length==2){o=m[0]
n=m[1]}}var l=n.split(";")
n=l[1]==""?[]:l[1].split(",")
p=l[0]
if(p&&p.indexOf("+")>0){l=p.split("+")
p=l[0]
var k=a[l[1]]
if(k instanceof Array)k=k[1]
for(var j in k){if(w.call(k,j)&&!w.call(r,j))r[j]=k[j]}}if(typeof dart_precompiled!="function"){u+=defineClass(o,s,n)
t.push(s)}if(p)y[s]=p}}if(typeof dart_precompiled!="function"){u+="return [\n  "+t.join(",\n  ")+"\n]"
var v=new Function("$collectedClasses",u)(a)
u=null}for(var i=0;i<v.length;i++){var h=v[i]
var s=h.name
var r=a[s]
var g=b
if(r instanceof Array){g=r[0]||b
r=r[1]}x[s]=h
g[s]=h}v=null
var f={}
init.interceptorsByTag=Object.create(null)
init.leafTags={}
function finishClass(a8){var e=Object.prototype.hasOwnProperty
if(e.call(f,a8))return
f[a8]=true
var d=y[a8]
if(!d||typeof d!="string")return
finishClass(d)
var a0=x[a8]
var a1=x[d]
if(!a1)a1=c[d]
var a2=z(a0,a1)
if(e.call(a2,"%")){var a3=a2["%"].split(";")
if(a3[0]){var a4=a3[0].split("|")
for(var a5=0;a5<a4.length;a5++){init.interceptorsByTag[a4[a5]]=a0
init.leafTags[a4[a5]]=true}}if(a3[1]){a4=a3[1].split("|")
if(a3[2]){var a6=a3[2].split("|")
for(var a5=0;a5<a6.length;a5++){var a7=x[a6[a5]]
a7.$nativeSuperclassTag=a4[0]}}for(a5=0;a5<a4.length;a5++){init.interceptorsByTag[a4[a5]]=a0
init.leafTags[a4[a5]]=false}}}}for(var s in y)finishClass(s)}
I.$lazy=function(a,b,c,d,e){var y={}
var x={}
a[c]=y
a[d]=function(){var w=$[c]
try{if(w===y){$[c]=x
try{w=$[c]=e()}finally{if(w===y){if($[c]===x){$[c]=null}}}}else{if(w===x)H.ag(b)}return w}finally{$[d]=function(){return this[c]}}}}
I.$finishIsolateConstructor=function(a){var y=a.p
function Isolate(){var x=Object.prototype.hasOwnProperty
for(var w in y)if(x.call(y,w))this[w]=y[w]
function ForceEfficientMap(){}ForceEfficientMap.prototype=this
new ForceEfficientMap()}Isolate.prototype=a.prototype
Isolate.prototype.constructor=Isolate
Isolate.p=y
Isolate.$finishClasses=a.$finishClasses
return Isolate}}
})()
